### ISSUE TITLE
Coverable

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#161]
> \<timotimo\> 	hmm. how about a "coverable" bot that just spits out the lines that were covered by a snippet you ran?

I have no idea how to implement this, and I don't really know what *exactly* is it supposed to do. But I thought I'll write it down here just in case.

**Comment by timo** [comment]
setting MVM_COVERAGE_LOG to a path (may contain a %d that will get the PID filled in) gives you a line like "HIT filename line" for every line that was reached during execution.

this can give you a broad overview of what code paths your code hits, for example if you're not sure what iterator classes and which of their methods are responsible for a given for loop.

the way to output this will be a bit more complex and it might not be doable as a simple gist.

**Comment by MasterDuke17** [comment]
Would you want to exclude lines covered by `perl6 -e ''`?

**Comment by timo** [comment]
that's a difficult question, because lines that have been won't be reported again (that's the idea anyway).
the coverage thing knows nothing about the program's lifecycle, so it won't distinguish between stuff in the compiler and stuff in the user program; if you remove whatever's in -e '', you might end up throwing away lines that got run in the user program - especially if they EVAL.

so i say: keep it. or maybe one day i'll build an nqp op that signals a transition between compiler and target or something

**Comment by AlexDaniel** [comment]
@MasterDuke17++ is working on it.

Example: https://gist.github.com/09ff8aa7ac91a8325a5ae54ac5f0c404

Feedback is welcome.

**Comment by AlexDaniel** [comment]
Latest output: https://gist.github.com/Whateverable/a65c0f5ea1f62c274af3a53d5135d3c6

**Comment by AlexDaniel** [comment]
It was committed in 54cc2c99dce03843cb87edf7f0308074232ca018. Tests needed, and I'd also say that some refactoring is required also :)

**Comment by AlexDaniel** [comment]
Some basic tests were added, closing.
